application:
  port: 8000
database: 
  host: "localhost"
  port: 5432
  username: "your_username"
  password: "your_password"
  database_name: "bot"
matrix: 
  username: "bot_username"
  password: "bot_password"